sudo: required
dist: trusty
language: generic
addons:
  hosts:
    - example.com
    - local.example.com
    - production.example.com
    - www.example.com
before_install:
  # node setup (for yeoman/bower)
  - nvm install 0.10
  - node --version
  - npm --version
  - nvm --version
  - npm install -g bower
  - npm install
  # ruby setup (for capistrano)
  - rvm use 1.9.3
  - gem install bundler
  - ruby --version
  - rvm --version
  - gem --version
  - bundle --version
  # python setup (for ansible)
  - sudo pip install ansible==1.9.4
  - python --version
  - pip --version
  - ansible --version
  # mock up test project, and move to /vagrant for end-user tests
  - $PWD/bin/mock
  - sudo ln -s $PWD/temp /vagrant
  - sudo chown -h $USER:$USER /vagrant
  # copy our local evolution-wordpress as bower dependency
  - rm -rf $PWD/temp/bower_components/evolution-wordpress
  - rsync -avz --exclude temp $PWD/ $PWD/temp/bower_components/evolution-wordpress/
  # invoke local provision (as default user with elevated permissions)
  - sudo cp $PWD/.travis.provision.bin $PWD/bin/provision
  - sudo chmod +x $PWD/bin/provision
  - sudo $PWD/bin/provision
  - sudo chown -Rf $USER:$USER $HOME/.ansible
  # mock vagrant binary (for parity with local/remote stages)
  - sudo cp $PWD/.travis.vagrant.bin /bin/vagrant
  - sudo chmod +x /bin/vagrant
  # ensure known ssh fingerprints for remote stages
  - ssh-keyscan -H production.example.com >> $HOME/.ssh/known_hosts
  - ssh-keyscan -H www.example.com >> $HOME/.ssh/known_hosts
  - ssh-keyscan -H example.com >> $HOME/.ssh/known_hosts
  # install composer (for phpunit)
  - curl -sS https://getcomposer.org/installer | php
install:
  - echo "Install Composer dependencies"
  - php composer.phar install --dev
script:
  - ./vendor/bin/phpunit
  - npm test
